### ISSUE TITLE
kdenlive crashes at launch

### ISSUE THREAD

**Issue by makruiten** [UnitedRPMs/packages#34]
Hi,

I'm unable to launch kdenlive on Fedora 24, installed from UnitedRPMs. I'm not sure where to look for error logs. My installation is upgraded from Fedora 23 with UnitedRPMs enabled beforehand, --allowerasing --best, no conflicts. It was working before the upgrade (when it was installed from the official repo). Please tell me where to look, so we can track this issue down.

**Comment by paulcarroty** [comment]
Hello, try to install

```
dnf install dnf install "kf5-kinit(x86-64)" 
```

https://github.com/UnitedRPMs/kdenlive/issues/1

@sergiomb2

**Comment by sergiomb2** [comment]
@makruiten it fix or not ?

**Comment by makruiten** [comment]
That package is already installed.

**Comment by sergiomb2** [comment]
so not fixed , I have to check , and yes the package is supposed to be install , do have mlt.f24 updated it ?

**Comment by paulcarroty** [comment]
@sergiomb2, we now have updated mlt 6.2 in URPMS.

**Comment by makruiten** [comment]
Yes, 6.0.2-1 was already installed. It says "kdenlive is crashed" before ever seeing the gui. Just a message in the gnome message center, that's all. Aren't there any logs to see what's happening?

**Comment by makruiten** [comment]
I also uninstalled qgnomeplatform to be sure it isn't related. I didn't reboot after removing it though. qgnomeplatform is installed per default for Fedora 24, right?

**Comment by paulcarroty** [comment]
@makruiten try to install the previous version:

```
dnf install https://github.com/UnitedRPMs/kdenlive/raw/39dd3dc057b8f3e52a17520f7f816bf6948f7ff7/kdenlive-15.12.2-2.fc24.x86_64.rpm
```

I think this is problem with mlt.

> qgnomeplatform is installed per default for Fedora 24, right?

AFAIR, yes.

**Comment by makruiten** [comment]
The old version still crashes. I'm not dependent on kdenlive, although I do use it, so I've got no problems with doing some additional tests and I'm not in a hurry. I do not have any other repos enabled at the moment, except for some small copr repos with one or two packages, so I can imagine that this is a problem more people are, or will be, experiencing. If it's mlt related, I guess there is not much I can do now?

**Comment by kuboosoft** [comment]
rebuild our mlt...

**Comment by ferral** [comment]
That's because of mlt is builded with qt4 (instead of qt5) or something like this. From what i read over internet - kdenlive loads qt5 libs for himself and qt4 for mlt - crash as result. I guess you can figure what exactly it is about - i remember that i did - ldd libmltqt.so (not sure bout filename) and it leds to qt4.

@makruiten there is working solution - find  libQtGui.so.4  (something like /usr/lib64/libQtGui.so.4 ) an rename it (to llllllll for example) (actually you can even delete it - it will reborn after reboot or even may be logout) - after that kdenlive will work

Sorry for worst english evar =)))

**Comment by sergiomb2** [comment]
Hello, yeah MLT must compile with qt5 , that why  I asked for the version , I may do the build in a bad way I have to check

**Comment by sergiomb2** [comment]
err , MLT is with wrong version of qt  
ldd /usr/lib64/mlt/libmltqt.so
rpm -qf /lib64/libQtCore.so.4
qt-4.8.7-17.fc24.x86_64

instead libQt5Core.so.5 , I will fix this soon (today)

**Comment by sergiomb2** [comment]
should be fixed

**Comment by sergiomb2** [comment]
it is fixed I just test it, please reopen if not

**Comment by makruiten** [comment]
It still doesn't start, but now no crash message appears either.

**Comment by sergiomb2** [comment]
as root you may run : 

    dnf debuginfo-install kdenlive-16.04.1-1.fc24.x86_64

will install, about 5 Gb of packages ... with regular user you may run on konsole : 

    gdb kdenlive
    run

when stops run bt (backtrace) unde gdb and post here the result please . 
Thanks

**Comment by kuboosoft** [comment]
Well, I made some changes, and it works. I'm running kdenlive, Tomorrow I will sync kdenlive.

![Image of kdenlive](http://s33.postimg.org/rtcafkx8v/kdenlive.png
)

**Comment by sergiomb2** [comment]
Try do the minimal changes , to be upstream to RPMFusion please , I maintain kdenlive with Rex ...

**Comment by kuboosoft** [comment]
Minimal changes; don't worry :)

**Comment by paulcarroty** [comment]
Very strange, it works 3 days ago in F24 KDE spin.

**Comment by sergiomb2** [comment]
works for me, both, kdenlive and openshot-qt ...

**Comment by kuboosoft** [comment]
@paucarroty; @sergiomb2 I use virtual machines with gnome...

**Comment by kuboosoft** [comment]
@paulcarroty; @sergiomb2 I use virtual machines with gnome... my default desktop is XFCE :)

**Comment by sergiomb2** [comment]
new kdenlive-16.04.1-2.fc24 and openshot-2.0.7-3.fc24 should be on all mirrors in a few minutes , please test it !

**Comment by makruiten** [comment]
Fixed, thanks! Starts without issues.
